return {
	kind = {
		Text = " ",
		Method = " ",
		Function = " ",
		Constructor = " ",
		Field = " ",
		Variable = " ",
		Class = " ",
		Interface = " ",
		Module = " ",
		Property = " ",
		Unit = " ",
		Value = " ",
		Enum = " ",
		Keyword = " ",
		Snippet = " ",
		Color = " ",
		File = " ",
		Reference = " ",
		Folder = " ",
		EnumMember = " ",
		Constant = " ",
		Struct = " ",
		Event = " ",
		Operator = " ",
		TypeParameter = " ",
		Misc = " ",
	},
	type = {
		Array = " ",
		Number = " ",
		String = " ",
		Boolean = " ",
		Object = " ",
	},
	documents = {
		File = " ",
		Files = " ",
		Folder = " ",
		OpenFolder = " ",
	},
	git = {
		Add = " ",
		Mod = " ",
		Remove = " ",
		Ignore = " ",
		Rename = " ",
		Diff = " ",
		Repo = " ",
		Branch = " ",
	},
	ui = {
		Lock = " ",
		Circle = " ",
		BigCircle = " ",
		BigUnfilledCircle = " ",
		Close = " ",
		NewFile = " ",
		Search = " ",
		Lightbulb = " ",
		Project = " ",
		Dashboard = " ",
		History = " ",
		Comment = " ",
		Bug = " ",
		Code = " ",
		Picker = " ",
		Gear = " ",
		Package = " ",
		List = " ",
		SignIn = " ",
		Check = " ",
		Fire = " ",
		Note = " ",
		BookMark = " ",
		Pencil = " ",
		ChevronRight = "",
		Table = " ",
		Calendar = " ",
	},
	diagnostics = {
		Error = " ",
		Warning = " ",
		Information = " ",
		Question = " ",
		Hint = " ",
	},
	misc = {
		Robot = " ",
		Tag = " ",
		Watch = " ",
	},
}
