local status_ok, snacks = pcall(require, "snacks")
if not status_ok then
	vim.notify("snacks.nvim did not load", vim.log.levels.WARN)
	return
end

snacks.setup({
	input = { enabled = true },
	notifier = {
		enabled = true,
		timeout = 3000,
	},
	picker = { enabled = true },
	quickfile = { enabled = true },
	words = { enabled = true },
})

local Snacks = snacks

local function map(lhs, rhs, desc, mode)
	vim.keymap.set(mode or "n", lhs, rhs, { silent = true, desc = desc })
end

map("<leader><space>", function()
	Snacks.picker.smart()
end, "Smart find")
map("<leader>,", function()
	Snacks.picker.buffers()
end, "Buffers")
map("<leader>/", function()
	Snacks.picker.grep()
end, "Grep")
map("<leader>:", function()
	Snacks.picker.command_history()
end, "Command history")

map("<leader>fb", function()
	Snacks.picker.buffers()
end, "Buffers")
map("<leader>fc", function()
	Snacks.picker.files({ cwd = vim.fn.stdpath("config") })
end, "Find config file")
map("<leader>ff", function()
	Snacks.picker.files()
end, "Find files")
map("<leader>fg", function()
	Snacks.picker.grep()
end, "Live grep")
map("<leader>fG", function()
	Snacks.picker.git_files()
end, "Find git files")
map("<leader>fp", function()
	Snacks.picker.projects()
end, "Projects")
map("<leader>fr", function()
	Snacks.picker.recent()
end, "Recent files")
map("<leader>fh", function()
	Snacks.picker.help()
end, "Help")

map("<leader>gb", function()
	Snacks.picker.git_branches()
end, "Git branches")
map("<leader>gl", function()
	Snacks.picker.git_log()
end, "Git log")
map("<leader>gL", function()
	Snacks.picker.git_log_line()
end, "Git log line")
map("<leader>gs", function()
	Snacks.picker.git_status()
end, "Git status")
map("<leader>gS", function()
	Snacks.picker.git_stash()
end, "Git stash")
map("<leader>gd", function()
	Snacks.picker.git_diff()
end, "Git diff")
map("<leader>gf", function()
	Snacks.picker.git_log_file()
end, "Git log file")

map("<leader>sb", function()
	Snacks.picker.lines()
end, "Buffer lines")
map("<leader>sB", function()
	Snacks.picker.grep_buffers()
end, "Grep open buffers")
map("<leader>sg", function()
	Snacks.picker.grep()
end, "Grep")
map("<leader>sw", function()
	Snacks.picker.grep_word()
end, "Grep word or selection", { "n", "x" })
map('<leader>s"', function()
	Snacks.picker.registers()
end, "Registers")
map("<leader>s/", function()
	Snacks.picker.search_history()
end, "Search history")
map("<leader>sa", function()
	Snacks.picker.autocmds()
end, "Autocmds")
map("<leader>sc", function()
	Snacks.picker.command_history()
end, "Command history")
map("<leader>sC", function()
	Snacks.picker.commands()
end, "Commands")
map("<leader>sd", function()
	Snacks.picker.diagnostics()
end, "Diagnostics")
map("<leader>sD", function()
	Snacks.picker.diagnostics_buffer()
end, "Buffer diagnostics")
map("<leader>sh", function()
	Snacks.picker.help()
end, "Help")
map("<leader>sH", function()
	Snacks.picker.highlights()
end, "Highlights")
map("<leader>sj", function()
	Snacks.picker.jumps()
end, "Jumps")
map("<leader>sk", function()
	Snacks.picker.keymaps()
end, "Keymaps")
map("<leader>sl", function()
	Snacks.picker.loclist()
end, "Location list")
map("<leader>sm", function()
	Snacks.picker.marks()
end, "Marks")
map("<leader>sM", function()
	Snacks.picker.man()
end, "Man pages")
map("<leader>sp", function()
	Snacks.picker.lazy()
end, "Plugin specs")
map("<leader>sq", function()
	Snacks.picker.qflist()
end, "Quickfix list")
map("<leader>sR", function()
	Snacks.picker.resume()
end, "Resume picker")
map("<leader>su", function()
	Snacks.picker.undo()
end, "Undo history")

map("gd", function()
	Snacks.picker.lsp_definitions()
end, "Go to definition")
map("gD", function()
	Snacks.picker.lsp_declarations()
end, "Go to declaration")
map("gr", function()
	Snacks.picker.lsp_references()
end, "References")
map("gI", function()
	Snacks.picker.lsp_implementations()
end, "Go to implementation")
map("gy", function()
	Snacks.picker.lsp_type_definitions()
end, "Go to type definition")
map("<leader>ss", function()
	Snacks.picker.lsp_symbols()
end, "LSP symbols")
map("<leader>sS", function()
	Snacks.picker.lsp_workspace_symbols()
end, "Workspace symbols")
